version: '3.9'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminadmin@123
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro   # Make sure prometheus.yml exists
    restart: unless-stopped

networks:
  monitoring:
    driver: host
